name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: linux-x86_64
            binary_path: target/release/peckr
            binary_name: peckr-linux-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            name: macos-x86_64
            binary_path: target/release/peckr
            binary_name: peckr-macos-x86_64

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build Release
      run: cargo build --verbose --release --target ${{ matrix.target }}
      
    - name: Prepare Binary
      shell: bash
      run: |
        cp ${{ matrix.binary_path }} ${{ matrix.binary_name }}
        
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.binary_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        name: Release ${{ github.ref_name }}
        generate_release_notes: true
